title: Pipeline generator
description: A tool able to generate the YAML resource of a job
theme: just-the-docs
url: https://just-the-docs.github.io

permalink: pretty

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
