title: Pipeline generator
description: A tool able to generate the YAML resource of a job
theme: just-the-docs
url: https://ch007m.github.com/pipeline-dsl-doc

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/ch007m/pipeline-dsl-doc

permalink: pretty

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
